name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google,Facebook,Email supported)
version: 1.0.7+2
author: Nicholas Bowler <crucifixx25@gmail.com>
homepage: https://github.com/zh1lu0/firebase_ui

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.3+4
  firebase_dynamic_links: ^0.5.0
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.6
  flutter_facebook_login: ^2.0.1
  email_validator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/double_ring_loading_io.gif

    - assets/fb-logo.png
    - assets/2.0x/fb-logo.png
    - assets/3.0x/fb-logo.png

    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/twitter-logo.png
    - assets/2.0x/twitter-logo.png
    - assets/3.0x/twitter-logo.png
